


// Get references to the #generate element
//const passwordEl = document.getElementById ('password')
//const lengthel= document.getElementById ('length')
//const lowerEl = document.getElementById ('lower')
//const upperEl = document.getElementById ('upper')
//const numberEl = document.getElementById ('number')
//const symbolEl = document.getElementById ('symbol')

//const randomFunc = {
  //lower: getRandomLower,
  //upper: getRandomUpper,
  //number: getRandomNumber,
  //symbol: getRandomSymbol,
  
//};






// Assignment code here
//Character Selector Section
// Functions for generating random characters
// Upper case , lower case, and numbers are pulled from CharCode Sheet
// special characters generated by inputing directly 

//function getRandomLower() {
  //return String.fromCharCode(Math.floor(Math.random() * 26) + 97);
//}
//console.log (getRandomLower());

//function getRandomUpper() {
  //return String.fromCharCode(Math.floor(Math.random() * 26) + 65);
//}
//console.log (getRandomUpper());

//function getRandomNumber() {
  //return String.fromCharCode(Math.floor(Math.random() * 10) + 48);
//}
//console.log(getRandomNumber());

function getRandomSymbol() {
  const symbols = '!@#$%^&*(){}[]+<>/,.?"\|;:`~-_';
  return symbols [Math.floor(Math.random() * symbols.length)];
}

function generatePassword() {
  var length = 5;
  var symbols = generatePassword();
}



// Get references to the #generate element
var generateBtn = document.querySelector("#generate");

// Write password to the #password input
function writePassword() {
  var password = generatePassword();
  var passwordText = document.querySelector("#password");

  passwordText.value = password;

}

// Add event listener to generate button
generateBtn.addEventListener("click", writePassword);
   

